"use client";

import { Bot, CheckCircle2, Headset, MessageCircle, Send, Sparkles, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type ChatMessage = { id: string | number; from: "assistant" | "user" | "agent"; text: string; senderName?: string };
const QUICK_QUESTIONS = ["How does the free trial work?", "How do I resume a session?", "I need help with billing"] as const;
const ANSWERS = [
  { keywords: ["trial", "free", "three", "month"], answer: "The free trial includes up to three EUR/USD replay sessions. Each session covers one month of historical data, with no payment required." },
  { keywords: ["resume", "session", "continue", "saved"], answer: "Open your Dashboard or Sessions page, choose a saved session, and select Resume. Your replay progress and trades are saved automatically." },
  { keywords: ["bill", "billing", "payment", "plan", "subscription", "paddle", "cancel"], answer: "You can review your plan and billing from Account → Billing. For payment failures, cancellations, or account-specific questions, our support team can help directly." },
  { keywords: ["chart", "replay", "play", "speed", "candle", "trade", "buy", "sell"], answer: "Use the replay controls below the chart to play, pause, change speed, and select a step interval. Buy and Sell execute simulated trades immediately." },
  { keywords: ["data", "pair", "market", "forex", "historical"], answer: "ForexTestLab uses historical market data for replay and simulated execution. Available pairs and date ranges depend on your plan." },
];
const answerQuestion = (question: string) => ANSWERS.find((entry) => entry.keywords.some((keyword) => question.toLowerCase().includes(keyword)))?.answer ?? "I don’t have a reliable answer for that yet. Our support team can review the details and help you directly.";

export function SupportChatWidget() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [visitorId, setVisitorId] = useState(""); const [conversationId, setConversationId] = useState(""); const [agentName, setAgentName] = useState<string | null>(null); const [chatStatus, setChatStatus] = useState<"idle" | "waiting" | "active" | "resolved">("idle"); const [sending, setSending] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([{ id: 1, from: "assistant", text: "Hi! I can help with common ForexTestLab questions. What would you like to know?" }]);

  useEffect(() => { const existing = window.localStorage.getItem("forextestlab_support_visitor") || crypto.randomUUID(); window.localStorage.setItem("forextestlab_support_visitor", existing); setVisitorId(existing); setConversationId(window.localStorage.getItem("forextestlab_support_conversation") || ""); }, []);
  useEffect(() => {
    if (!conversationId || !visitorId || chatStatus === "resolved") return;
    const refresh = async () => {
      const response = await fetch(`/api/support/chat?conversationId=${encodeURIComponent(conversationId)}&visitorId=${encodeURIComponent(visitorId)}`, { cache: "no-store" });
      if (!response.ok) return;
      const payload = await response.json() as { conversation?: { status: string; assignedAgentName?: string | null; messages: Array<{ id: string; senderType: string; senderName: string; body: string }> } | null };
      if (!payload.conversation) return;
      setChatStatus(payload.conversation.status as "waiting" | "active" | "resolved");
      setAgentName(payload.conversation.assignedAgentName || null);
      setMessages(payload.conversation.messages.map((item) => ({ id: item.id, from: item.senderType === "customer" ? "user" : item.senderType === "agent" ? "agent" : "assistant", text: item.body, senderName: item.senderName })));
    };
    void refresh(); const timer = window.setInterval(refresh, 5000); return () => window.clearInterval(timer);
  }, [conversationId, visitorId, chatStatus]);
  function ask(question: string) { const trimmed = question.trim(); if (!trimmed) return; setMessages((current) => [...current, { id: crypto.randomUUID(), from: "user", text: trimmed }, { id: crypto.randomUUID(), from: "assistant", text: answerQuestion(trimmed) }]); setInput(""); }
  async function requestAgent() { if (!visitorId || sending) return; const text = input.trim() || "I need help from the support team."; setSending(true); try { const response = await fetch("/api/support/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: conversationId ? "message" : "start", conversationId, visitorId, message: text }) }); const payload = await response.json() as { ok: boolean; conversation?: { id: string; messages: Array<{ id: string; senderType: string; senderName: string; body: string }> } }; if (!payload.ok || !payload.conversation) return; setConversationId(payload.conversation.id); window.localStorage.setItem("forextestlab_support_conversation", payload.conversation.id); setChatStatus("waiting"); setInput(""); setMessages(payload.conversation.messages.map((item) => ({ id: item.id, from: item.senderType === "customer" ? "user" : item.senderType === "agent" ? "agent" : "assistant", text: item.body, senderName: item.senderName }))); } finally { setSending(false); } }
  return <>
    {open && <section className="fixed bottom-24 right-4 z-[80] flex w-[min(calc(100vw-2rem),380px)] flex-col overflow-hidden rounded-2xl border border-white/15 bg-surface-900 shadow-2xl shadow-black/40" aria-label="ForexTestLab support assistant">
      <header className="flex items-center justify-between border-b border-white/10 bg-[linear-gradient(135deg,rgba(34,195,160,.18),rgba(17,23,37,.7))] px-4 py-3.5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-400/15 text-brand-300">{agentName ? <Headset size={18} aria-hidden /> : <Bot size={18} aria-hidden />}</span><div><p className="text-sm font-semibold text-white">{agentName || "Support assistant"}</p><p className="mt-0.5 text-[11px] text-slate-400">{agentName ? "Live support · replying here" : "Quick answers for common questions"}</p></div></div><button type="button" onClick={() => setOpen(false)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-white/10 hover:text-white" aria-label="Close support assistant"><X size={17} aria-hidden /></button></header>
      <div className="max-h-[min(48vh,390px)] space-y-3 overflow-y-auto p-4" aria-live="polite">{messages.map((message) => <div key={message.id} className={`flex ${message.from === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-3.5 py-2.5 text-xs leading-5 ${message.from === "user" ? "rounded-br-md bg-brand-500 text-surface-950" : message.from === "agent" ? "rounded-bl-md border border-brand-400/20 bg-brand-400/10 text-slate-200" : "rounded-bl-md bg-surface-800 text-slate-300"}`}>{message.from !== "user" && message.senderName && <p className="mb-1 text-[10px] font-semibold text-brand-300">{message.senderName}</p>}{message.text}</div></div>)}{chatStatus === "waiting" && <div className="flex items-center gap-2 rounded-xl border border-amber-300/20 bg-amber-300/5 px-3 py-2.5 text-[11px] text-amber-100"><Headset size={13} /> A support agent will join shortly.</div>}{chatStatus === "active" && agentName && <div className="flex items-center gap-2 text-[11px] text-brand-200"><CheckCircle2 size={13} /> {agentName} has joined the conversation.</div>}<div className="flex items-center gap-2 rounded-xl border border-brand-400/15 bg-brand-400/[0.05] px-3 py-2.5 text-[11px] text-slate-400"><Sparkles size={13} className="shrink-0 text-brand-300" /> Need something more specific? <Link href="/support" onClick={() => setOpen(false)} className="font-semibold text-brand-300 hover:text-brand-200">Contact support</Link></div></div>
      <div className="border-t border-white/10 px-3 pb-3 pt-2.5"><div className="mb-2 flex gap-1.5 overflow-x-auto pb-1">{QUICK_QUESTIONS.map((question) => <button key={question} type="button" onClick={() => ask(question)} className="shrink-0 rounded-full border border-white/10 bg-surface-800 px-2.5 py-1.5 text-[10px] font-medium text-slate-300 hover:border-brand-400/30 hover:text-brand-200">{question}</button>)}<button type="button" onClick={() => void requestAgent()} className="shrink-0 rounded-full border border-brand-400/30 bg-brand-400/10 px-2.5 py-1.5 text-[10px] font-semibold text-brand-200">Talk to a person</button></div><form onSubmit={(event) => { event.preventDefault(); if (conversationId) void requestAgent(); else ask(input); }} className="flex items-center gap-2"><input value={input} onChange={(event) => setInput(event.target.value)} placeholder={conversationId ? "Message support…" : "Ask a question…"} aria-label="Message support" className="app-input min-w-0 flex-1 py-2.5 text-xs" /><button type="submit" disabled={sending || chatStatus === "resolved"} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand-500 text-surface-950 hover:bg-brand-400 disabled:opacity-50" aria-label="Send message"><Send size={15} aria-hidden /></button></form></div>
    </section>}
    <button type="button" onClick={() => setOpen((current) => !current)} className="fixed bottom-5 right-4 z-[80] inline-flex items-center gap-2 rounded-full border border-brand-300/30 bg-brand-500 px-4 py-3 text-xs font-bold text-surface-950 shadow-glow transition-transform hover:-translate-y-0.5" aria-expanded={open} aria-controls="support-assistant-panel"><MessageCircle size={17} aria-hidden /> Help</button>
  </>;
}
